lib/todo_practice_web/router.ex
defmodule TodoPracticeWeb.Router do
  use TodoPracticeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TodoPracticeWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    get "/tesla", TodoPracticeWeb.TeslaController, :get
    post "/tesla", TodoPracticeWeb.TeslaController, :create
    put "/tesla", TodoPracticeWeb.TeslaController, :update
    delete "/tesla", TodoPracticeWeb.TeslaController, :delete
  end

  scope "/", TodoPracticeWeb do
    pipe_through :browser

    get "/", PageController, :index
    live "/todos", TodoLive.Index, :index
    live "/todos/new", TodoLive.Index, :new
    live "/todos/:id/edit", TodoLive.Index, :edit

    live "/todos/:id", TodoLive.Show, :show
    live "/todos/:id/show/edit", TodoLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", TodoPracticeWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: TodoPracticeWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/todo_practice_web/live/live_helpers.ex
defmodule TodoPracticeWeb.LiveHelpers do
  import Phoenix.LiveView
  import Phoenix.LiveView.Helpers

  alias Phoenix.LiveView.JS

  @doc """
  Renders a live component inside a modal.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <.modal return_to={Routes.todo_index_path(@socket, :index)}>
        <.live_component
          module={TodoPracticeWeb.TodoLive.FormComponent}
          id={@todo.id || :new}
          title={@page_title}
          action={@live_action}
          return_to={Routes.todo_index_path(@socket, :index)}
          todo: @todo
        />
      </.modal>
  """
  def modal(assigns) do
    assigns = assign_new(assigns, :return_to, fn -> nil end)

    ~H"""
    <div id="modal" class="phx-modal fade-in" phx-remove={hide_modal()}>
      <div
        id="modal-content"
        class="phx-modal-content fade-in-scale"
        phx-click-away={JS.dispatch("click", to: "#close")}
        phx-window-keydown={JS.dispatch("click", to: "#close")}
        phx-key="escape"
      >
        <%= if @return_to do %>
          <%= live_patch "✖",
            to: @return_to,
            id: "close",
            class: "phx-modal-close",
            phx_click: hide_modal()
          %>
        <% else %>
          <a id="close" href="#" class="phx-modal-close" phx-click={hide_modal()}>✖</a>
        <% end %>

        <%= render_slot(@inner_block) %>
      </div>
    </div>
    """
  end

  defp hide_modal(js \\ %JS{}) do
    js
    |> JS.hide(to: "#modal", transition: "fade-out")
    |> JS.hide(to: "#modal-content", transition: "fade-out-scale")
  end
end

lib/todo_practice_web/live/todo_live/form_component.ex
defmodule TodoPracticeWeb.TodoLive.FormComponent do
  use TodoPracticeWeb, :live_component

  alias TodoPractice.Todos

  @impl true
  def update(%{todo: todo} = assigns, socket) do
    changeset = Todos.change_todo(todo)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"todo" => todo_params}, socket) do
    changeset =
      socket.assigns.todo
      |> Todos.change_todo(todo_params)
      |> Map.put(:action, :validate)
      
    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"todo" => todo_params}, socket) do
    save_todo(socket, socket.assigns.action, todo_params)
  end

  defp save_todo(socket, :edit, todo_params) do
    case Todos.update_todo(socket.assigns.todo, todo_params) do
      {:ok, _todo} ->
        {:noreply,
         socket
         |> put_flash(:info, "Todo updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_todo(socket, :new, todo_params) do
    case Todos.create_todo(todo_params) do
      {:ok, _todo} ->
        {:noreply,
         socket
         |> put_flash(:info, "Todo created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/todo_practice_web/live/todo_live/index.ex
defmodule TodoPracticeWeb.TodoLive.Index do
  use TodoPracticeWeb, :live_view

  alias TodoPractice.Todos
  alias TodoPractice.Todos.Todo

  @impl true
  def mount(_params, _session, socket) do
    {:ok,
     socket
     |> assign(:filter, "없음")
     |> assign(:todos, list_todos())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Todo")
    |> assign(:todo, Todos.get_todo!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Todo")
    |> assign(:todo, %Todo{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Todos")
    |> assign(:todo, nil)
  end

  def handle_event("filter_all", _value, socket) do
    {:noreply,
     socket
     |> assign(:filter, "All")
     |> assign(:todos, list_todos())}
  end

  def handle_event("filter_high", _value, socket) do
    {:noreply,
     socket
     |> assign(:filter, "High")
     |> assign(:todos, TodoPractice.Todos.where_priority("High"))}
  end

  def handle_event("filter_middle", _value, socket) do
    {:noreply,
     socket
     |> assign(:filter, "Middle")
     |> assign(:todos, TodoPractice.Todos.where_priority("Middle"))}
  end

  def handle_event("filter_low", _value, socket) do
    {:noreply,
     socket
     |> assign(:filter, "Low")
     |> assign(:todos, TodoPractice.Todos.where_priority("Low"))}
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    todo = Todos.get_todo!(id)
    {:ok, _} = Todos.delete_todo(todo)

    {:noreply, assign(socket, :todos, list_todos())}
  end

  defp list_todos do
    Todos.list_todos()
  end
end

lib/todo_practice_web/live/todo_live/show.ex
defmodule TodoPracticeWeb.TodoLive.Show do
  use TodoPracticeWeb, :live_view

  alias TodoPractice.Todos

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:todo, Todos.get_todo!(id))}
  end

  defp page_title(:show), do: "Show Todo"
  defp page_title(:edit), do: "Edit Todo"
end

lib/todo_practice_web/live/todo_live/form_component.html.heex
<div>
  <h2><%= @title %></h2>

  <.form
    let={f}
    for={@changeset}
    id="todo-form"
    phx-target={@myself}
    phx-change="validate"
    phx-submit="save">
  
    <%= label f, :title %>
    <%= text_input f, :title %>
    <%= error_tag f, :title %>
  
    <%= label f, :complete %>
    <%= checkbox f, :complete %>
    <%= error_tag f, :complete %>
  
    <%= label f, :priority %>
    <%= text_input f, :priority %>
    <%= error_tag f, :priority %>
  
    <div>
      <%= submit "Save", phx_disable_with: "Saving..." %>
    </div>
  </.form>
</div>

lib/todo_practice_web/live/todo_live/index.html.heex
<h1>Listing Todos</h1>

<%= if @live_action in [:new, :edit] do %>
  <.modal return_to={Routes.todo_index_path(@socket, :index)}>
    <.live_component
      module={TodoPracticeWeb.TodoLive.FormComponent}
      id={@todo.id || :new}
      title={@page_title}
      action={@live_action}
      todo={@todo}
      return_to={Routes.todo_index_path(@socket, :index)}
    />
  </.modal>
<% end %>

<div>
<h1 style="color: red;" align="center">
  <%= @filter %>
</h1>
</div>
<div class="all">
  <button id="getAllTodosButton" phx-click="filter_all">Get All Todos</button>
</div>

<div class="getHighTodos">
  <button id="getAllTodosButton" phx-click="filter_high">Get High-Priority Todos</button>
</div>

<div class="getMiddleTodos">
  <button id="getAllTodosButton" phx-click="filter_middle">Get Middle-Priority Todos</button>
</div>

<div class="getLowTodos">
  <button id="getAllTodosButton" phx-click="filter_low">Get Low-Priority Todos</button>
</div>

<table>
  <thead>
    <tr align="center">
      <th > ID </th>
      <th>Title</th>
      <th>Complete</th>
      <th>Priority</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="todos" align="center">
    <%= for todo <- @todos do %>
      <tr id={"todo-#{todo.id}"}>
        <td><%= todo.id %></td>
        <td><%= todo.title %></td>
        <td><%= todo.complete %></td>
        <td><%= todo.priority %></td>

        <td>
          <span><%= live_redirect "Show", to: Routes.todo_show_path(@socket, :show, todo) %></span>
          <span><%= live_patch "Edit", to: Routes.todo_index_path(@socket, :edit, todo) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: todo.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


  <select id="todo_id" title="todo[todo_id]">
    <%= for todo <- @todos do %>
      <option><%= todo.title %></option>
    <% end %>
  </select>

<span><%= live_patch "New Todo", to: Routes.todo_index_path(@socket, :new) %></span>

lib/todo_practice_web/live/todo_live/show.html.heex
<h1>Show Todo</h1>

<%= if @live_action in [:edit] do %>
  <.modal return_to={Routes.todo_show_path(@socket, :show, @todo)}>
    <.live_component
      module={TodoPracticeWeb.TodoLive.FormComponent}
      id={@todo.id}
      title={@page_title}
      action={@live_action}
      todo={@todo}
      return_to={Routes.todo_show_path(@socket, :show, @todo)}
    />
  </.modal>
<% end %>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @todo.title %>
  </li>

  <li>
    <strong>Complete:</strong>
    <%= @todo.complete %>
  </li>

  <li>
    <strong>Priority:</strong>
    <%= @todo.priority %>
  </li>

</ul>

<span><%= live_patch "Edit", to: Routes.todo_show_path(@socket, :edit, @todo), class: "button" %></span> |
<span><%= live_redirect "Back", to: Routes.todo_index_path(@socket, :index) %></span>